services:
  db:
    image: postgres
    volumes:
      - ./src/main/resources/db:/var/lib/postgresgl/data
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d
    networks:
      - service-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shop
    ports:
      - "5433:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  product-cards-service:
    depends_on:
      - db
    restart: unless-stopped
    build: .
    networks:
      - service-network
    ports:
      - 7000:7000
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

networks:
  service-network: